### ISSUE TITLE
Laravel 5.7 compatibility

### ISSUE THREAD

**Issue by lexKiev** [parsidev/TCP-Socket#2]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v5.7.6
    - Conclusion: don't install laravel/framework v5.7.6
    - Conclusion: don't install laravel/framework v5.7.5
    - Conclusion: don't install laravel/framework v5.7.4
    - Conclusion: don't install laravel/framework v5.7.3
    - Conclusion: don't install laravel/framework v5.7.2
    - Installation request for parsidev/tcp-socket dev-master -> satisfiable by parsidev/tcp-socket[dev-master].
    - Conclusion: don't install laravel/framework v5.7.1
    - Conclusion: don't install laravel/framework v5.7.0
    - parsidev/tcp-socket dev-master requires illuminate/support 5.4.* -> satisfiable by illuminate/support[5.4.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9].
    - illuminate/support 5.4.x-dev conflicts with laravel/framework[5.7.x-dev].
    - illuminate/support v5.4.0 conflicts with laravel/framework[5.7.x-dev].
    - illuminate/support v5.4.13 conflicts with laravel/framework[5.7.x-dev].
    - illuminate/support v5.4.17 conflicts with laravel/framework[5.7.x-dev].
    - illuminate/support v5.4.19 conflicts with laravel/framework[5.7.x-dev].
    - illuminate/support v5.4.27 conflicts with laravel/framework[5.7.x-dev].
    - illuminate/support v5.4.36 conflicts with laravel/framework[5.7.x-dev].
    - illuminate/support v5.4.9 conflicts with laravel/framework[5.7.x-dev].
    - Installation request for laravel/framework 5.7.* -> satisfiable by laravel/framework[5.7.x-dev, v5.7.0, v5.7.1, v5.7.2, v5.7.3, v5.7.4, v5.7.5, v5.7.6].

**Comment by parsidev** [comment]
Please use this

```"parsidev/tcp-socket": "5.7.x-dev"```
