### ISSUE TITLE
Example please

### ISSUE THREAD

**Issue by scaleman114** [parsidev/TCP-Socket#4]
I am interested in this but I'm also a newbie do you have any demo projects?

**Comment by parsidev** [comment]
Hi @scaleman114 

```
$tcp = Parsidev\Socket\Facades\Socket::connect(SERVER_IP, SERVER_PORT, SOCKET_TYPE, TIMEOUT);
$msg = "hello world";
$response = Socket::sendMessage($tcp->socket, $msg);
echo $response;
```

just u need to enter your server ip in `SERVER_IP` and your port lisened in `SERVER_PORT` and SOCKET_TYPE is `SOL_TCP` or `SOL_UDP`, you can set connection timeout in `TIMEOUT`

**Comment by scaleman114** [comment]
Thanks, the sendMessage method differs from the readme and that was what was causing me a problem.
